### ISSUE TITLE
Nazwy klas w Javie - źle je napisałeś...

### ISSUE THREAD

**Issue by Mcpg** [mckondziu/CheckPlayer#1]
Wg. konwencji nazewnictwa w Javie od Oracle, wszystkie klasy mają zaczynać się z wielkiej litery, coś takiego jak:
OhYeaThisIsMyClassBaby

Ty masz klasy z małej. Rly? Radziłbym to poprawić - wtedy twój kod będzie bardziej profesjonalnie wyglądał. (Wszyscy szanujący się programiści Javy tak robią)

**Comment by mckondziu** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Dnia Piątek, 28 Sierpnia 2015 17:45 MCPlayG notifications@github.com napisał(a)

Wg. konwencji nazewnictwa w Javie od Oracle, wszystkie klasy mają zaczynać się z wielkiej litery, coś takiego jak: OhYeaThisIsMyClassBaby
Ty masz klasy z małej. Rly? Radziłbym to poprawić - wtedy twój kod będzie bardziej profesjonalnie wyglądał. (Wszyscy szanujący się programiści Javy tak robią)
—Reply to this email directly or view it on GitHub.
 

 Tak, zgodzę się z tobą. Ten plugin muszę bardziej poprawić, bo mimo to że napisałem po swojemu i trochę dodałem do pluginu to mógł by być bardziej wydajny i ładniej napisany, lecz też zobaczmy że plugin nie ma jeszcze wydanej pełnej wersji więc trzeba wybaczyć :PAle dziękuje za podpowiedź :)

**Comment by Mcpg** [comment]
Jaką podpowiedź? Na bukkit.pl ci wszyscy o tym spamią >.<
Ale nawet, jeśli nie jest to pełna wersja, to każdy szanujący się programista Javy musi klasy z Wielkiej litery zaczynać (to brzmi tak, jak.. eeem.. nie wiem co >.<)

**Comment by Mcpg** [comment]
A, i jeszcze coś, zauważyłem, że w jednym miejscu masz napisaną zmienną po polsku. XD To też łamie konwencje. ^-^

**Comment by mckondziu** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Dnia Sobota, 29 Sierpnia 2015 07:56 MCPlayG notifications@github.com napisał(a)

A, i jeszcze coś, zauważyłem, że w jednym miejscu masz napisaną zmienną po polsku. XD To też łamie konwencje. ^-^
—Reply to this email directly or view it on GitHub.
 

nie macie już się czego trzeciać? Tylko o takie małe gówna, jak Wielkie litery, zmiena po polsku, itp..."Bo każdy szanujący się programista Javy musi..." A może ja nie szanuje

**Comment by Mcpg** [comment]
Jak się nie szanujesz, to już inna sytuacja >.<

**Comment by mckondziu** [comment]
:P
